(autoload 'mapl-lookup-command                  "map-lines" "" nil)
(autoload 'map-lines                            "map-lines" "" t)
(autoload 'mapl-kill-line                       "map-lines" "" nil)
(autoload 'copy-line                            "map-lines" "" t)
(autoload 'mapl-copy-line                       "map-lines" "" nil)
(autoload 'mapl-kill-universal                  "map-lines" "" nil)
(autoload 'map-lines-kill                       "map-lines" "" t)
(autoload 'map-lines-copy                       "map-lines" "" t)
(provide 'map-lines-epackage-autoloads)
