(autoload 'map-lines                            "map-lines" "" t)
(autoload 'copy-line                            "map-lines" "" t)
(autoload 'map-lines-kill                       "map-lines" "" t)
(autoload 'map-lines-copy                       "map-lines" "" t)
(provide 'map-lines-epackage-autoloads)
